version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: ott-mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: admin
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    platform: linux/x86_64

  redis:
    container_name: ott-redis
    hostname: redis
    image: redis:alpine
    ports:
      - 6379:6379
    command: redis-server
    restart: always